// Mocks generated by Mockito 5.4.4 from annotations
// in omni_for_pyload/test/features/server/viewmodel/server_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:omni_for_pyload/domain/models/server.dart' as _i5;
import 'package:omni_for_pyload/domain/repositories/i_pyload_api_repository.dart'
    as _i3;
import 'package:omni_for_pyload/domain/repositories/i_server_repository.dart'
    as _i6;
import 'package:openapi_client/api.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeServerStatus_0 extends _i1.SmartFake implements _i2.ServerStatus {
  _FakeServerStatus_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePackageData_1 extends _i1.SmartFake implements _i2.PackageData {
  _FakePackageData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IPyLoadApiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPyLoadApiRepository extends _i1.Mock
    implements _i3.IPyLoadApiRepository {
  MockIPyLoadApiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ServerStatus> getServerStatus(_i5.Server? server) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServerStatus,
          [server],
        ),
        returnValue: _i4.Future<_i2.ServerStatus>.value(_FakeServerStatus_0(
          this,
          Invocation.method(
            #getServerStatus,
            [server],
          ),
        )),
      ) as _i4.Future<_i2.ServerStatus>);

  @override
  _i4.Future<List<_i2.DownloadInfo>> getDownloadStatus(_i5.Server? server) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDownloadStatus,
          [server],
        ),
        returnValue:
            _i4.Future<List<_i2.DownloadInfo>>.value(<_i2.DownloadInfo>[]),
      ) as _i4.Future<List<_i2.DownloadInfo>>);

  @override
  _i4.Future<List<_i2.PackageData>> getQueueData(_i5.Server? server) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQueueData,
          [server],
        ),
        returnValue:
            _i4.Future<List<_i2.PackageData>>.value(<_i2.PackageData>[]),
      ) as _i4.Future<List<_i2.PackageData>>);

  @override
  _i4.Future<List<_i2.PackageData>> getCollectorData(_i5.Server? server) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollectorData,
          [server],
        ),
        returnValue:
            _i4.Future<List<_i2.PackageData>>.value(<_i2.PackageData>[]),
      ) as _i4.Future<List<_i2.PackageData>>);

  @override
  _i4.Future<List<_i2.PackageData>> getQueue(_i5.Server? server) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQueue,
          [server],
        ),
        returnValue:
            _i4.Future<List<_i2.PackageData>>.value(<_i2.PackageData>[]),
      ) as _i4.Future<List<_i2.PackageData>>);

  @override
  _i4.Future<List<_i2.PackageData>> getCollector(_i5.Server? server) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollector,
          [server],
        ),
        returnValue:
            _i4.Future<List<_i2.PackageData>>.value(<_i2.PackageData>[]),
      ) as _i4.Future<List<_i2.PackageData>>);

  @override
  _i4.Future<_i2.PackageData> getPackageData(
    _i5.Server? server,
    int? packageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackageData,
          [
            server,
            packageId,
          ],
        ),
        returnValue: _i4.Future<_i2.PackageData>.value(_FakePackageData_1(
          this,
          Invocation.method(
            #getPackageData,
            [
              server,
              packageId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.PackageData>);

  @override
  _i4.Future<void> deletePackages(
    _i5.Server? server,
    List<int>? packageIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePackages,
          [
            server,
            packageIds,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.Result> restartPackages(
    _i5.Server? server,
    List<int>? packageIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #restartPackages,
          [
            server,
            packageIds,
          ],
        ),
        returnValue: _i4.Future<_i3.Result>.value(_i3.Result.success),
      ) as _i4.Future<_i3.Result>);

  @override
  _i4.Future<_i3.Result> movePackages(
    _i5.Server? server,
    List<int>? packageIds,
    _i2.Destination? destination,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #movePackages,
          [
            server,
            packageIds,
            destination,
          ],
        ),
        returnValue: _i4.Future<_i3.Result>.value(_i3.Result.success),
      ) as _i4.Future<_i3.Result>);

  @override
  _i4.Future<_i3.Result> extractPackages(
    _i5.Server? server,
    List<int>? packageIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractPackages,
          [
            server,
            packageIds,
          ],
        ),
        returnValue: _i4.Future<_i3.Result>.value(_i3.Result.success),
      ) as _i4.Future<_i3.Result>);

  @override
  _i4.Future<void> pauseServer(_i5.Server? server) => (super.noSuchMethod(
        Invocation.method(
          #pauseServer,
          [server],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unpauseServer(_i5.Server? server) => (super.noSuchMethod(
        Invocation.method(
          #unpauseServer,
          [server],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stopAllDownloads(_i5.Server? server) => (super.noSuchMethod(
        Invocation.method(
          #stopAllDownloads,
          [server],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteFinished(_i5.Server? server) => (super.noSuchMethod(
        Invocation.method(
          #deleteFinished,
          [server],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> restartFailed(_i5.Server? server) => (super.noSuchMethod(
        Invocation.method(
          #restartFailed,
          [server],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> uploadContainer(
    _i5.Server? server,
    String? fileName,
    List<int>? fileBytes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadContainer,
          [
            server,
            fileName,
            fileBytes,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> addPackage(
    _i5.Server? server,
    String? name,
    List<String>? links,
    _i2.Destination? destination,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPackage,
          [
            server,
            name,
            links,
            destination,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [IServerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIServerRepository extends _i1.Mock implements _i6.IServerRepository {
  MockIServerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Server>> getAllServers() => (super.noSuchMethod(
        Invocation.method(
          #getAllServers,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Server>>.value(<_i5.Server>[]),
      ) as _i4.Future<List<_i5.Server>>);

  @override
  _i4.Future<void> addServer(_i5.Server? server) => (super.noSuchMethod(
        Invocation.method(
          #addServer,
          [server],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> serverExists(
    String? ip,
    int? port,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #serverExists,
          [
            ip,
            port,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> removeServer(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeServer,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateServer(_i5.Server? server) => (super.noSuchMethod(
        Invocation.method(
          #updateServer,
          [server],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllServers() => (super.noSuchMethod(
        Invocation.method(
          #clearAllServers,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
