// Mocks generated by Mockito 5.4.4 from annotations
// in omni_for_pyload/test/features/add_server/viewmodel/add_server_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:omni_for_pyload/domain/models/server.dart' as _i4;
import 'package:omni_for_pyload/domain/repositories/i_pyload_api_repository.dart'
    as _i5;
import 'package:omni_for_pyload/domain/repositories/i_server_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IServerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIServerRepository extends _i1.Mock implements _i2.IServerRepository {
  MockIServerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Server>> getAllServers() => (super.noSuchMethod(
        Invocation.method(
          #getAllServers,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Server>>.value(<_i4.Server>[]),
      ) as _i3.Future<List<_i4.Server>>);

  @override
  _i3.Future<void> addServer(_i4.Server? server) => (super.noSuchMethod(
        Invocation.method(
          #addServer,
          [server],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> serverExists(
    String? ip,
    int? port,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #serverExists,
          [
            ip,
            port,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> removeServer(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeServer,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllServers() => (super.noSuchMethod(
        Invocation.method(
          #clearAllServers,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [IPyLoadApiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPyLoadApiRepository extends _i1.Mock
    implements _i5.IPyLoadApiRepository {
  MockIPyLoadApiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> testServerConnection(_i4.Server? server) =>
      (super.noSuchMethod(
        Invocation.method(
          #testServerConnection,
          [server],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
